steps:
  - name: 'node:slim'
    entrypoint: 'npm'
    args: ['install']
    dir: 'api/design'

  - name: 'node:slim'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'api/design'
  
  - name: 'node:slim'
    entrypoint: 'npm'
    args: ['run', 'build-html']
    dir: 'api/design'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp api/design/dist/*.yaml gs://foodstore-design-dev
        gsutil cp api/design/dist/*.html gs://foodstore-design-dev
        gsutil acl ch -u AllUsers:R gs://foodstore-design-dev/foodstore-dev.html


timeout: '600s'
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'
logsBucket: 'gs://foodstore-design-dev/logs'
options:
  logging: GCS_ONLY
  automapSubstitutions: true