steps:
  - name: 'node:slim'
    entrypoint: 'npm'
    args: ['install']
    dir: 'design'

  - name: 'node:slim'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'design'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp design/dist/*.yaml gs://foodstore-design-dev

timeout: '600s'
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'
logsBucket: 'gs://foodstore-design-dev'
options:
  logging: GCS_ONLY
  automapSubstitutions: true