openapi: 3.0.0
info:
  title: Definición de Smarrt Triage
  version: 1.0.0
paths:
  '/smart-triage':
    get:
      summary: Evaluate Smart Triage
      parameters:
        - in: header
          name: traceId
          required: true
          schema:
            type: string
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
        - in: header
          name: applicationName
          required: true
          schema:
            type: string
        - in: header
          name: channel
          required: true
          schema:
            type: string
            enum:
            - WEB
            - APP
            - OI
        - in: header
          name: provider
          required: true
          schema:
            type: string
            enum:
            - CUIDA
            - CI
            - AUNA
            - JOCKEY                  
      responses:
        '200':
          description: Petición exitosa 