export enum PiorityType {
    low = '1',
    medium = '2',
    high = '3',
}

export const piorityType = {
    '1': { display: "Baja", system: "https://fhir.onehealth.com.pe/CodeSystem/PrioritiesCodeSystemOH" },
    '2': { display: "Media", system: "https://fhir.onehealth.com.pe/CodeSystem/PrioritiesCodeSystemOH" },
    '3': { display: "Alta", system: "https://fhir.onehealth.com.pe/CodeSystem/PrioritiesCodeSystemOH" },
}

export enum ParticipantType {
    ADM = "ADM",
    ATND = "ATND",
    CALLBCK = "CALLBCK",
    CON = "CON",
    DIS = "DIS",
    ESC = "ESC",
    REF = "REF",
    SPRF = "SPRF",
    PPRF = "PPRF",
    PART = "PART",
    traslator = "traslator",
    emergency = "emergency",
}

export const participantType = {
    'ADM': { display: "admitter", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'ATND': { display: "attender", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'CALLBCK': { display: "callback contact", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'CON': { display: "consultant", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'DIS': { display: "discharger", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'ESC': { display: "escort", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'REF': { display: "referrer", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'SPRF': { display: "secondary performer", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'PPRF': { display: "primary performer", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'PART': { display: "Participation", system: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType" },
    'traslator': { display: "Traslator", system: "http://terminology.hl7.org/CodeSystem/participant-type" },
    'emergency': { display: "Emergency", system: "http://terminology.hl7.org/CodeSystem/participant-type" },
}

export enum ReasonCodeTypes {

}

export enum DiagnosisTypes {
    primario = "primario",
    secundario = "secundario",
    nodefinido = "no-definido",
    AD = "AD",
    DD = "DD",
    CC = "CC",
    CM = "CM",
    preop = "pre-op",
    postop = "post-op",
    billing = "billing",
}

export const diagnosisType = {
    primario: { display: "admitter", system: "https://fhir.onehealth.com.pe/CodeSystem/DiagnosisClassifications" },
    secundario: { display: "attender", system: "https://fhir.onehealth.com.pe/CodeSystem/DiagnosisClassifications" },
    nodefinido: { display: "callback contact", system: "https://fhir.onehealth.com.pe/CodeSystem/DiagnosisClassifications" },
    AD: { display: "Admission diagnosis", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    DD: { display: "Discharge diagnosis", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    CC: { display: "Chief complaint", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    CM: { display: "Comorbidity diagnosis", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    preop: { display: "pre-op diagnosis", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    postop: { display: "post-op diagnosis", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
    billing: { display: "Billing", system: "http://terminology.hl7.org/CodeSystem/diagnosis-role" },
}

export const typeType = {
    '440655000': { display: "Atención ambulatoria", system: "http://snomed.info/sct" },
    '410620009': { display: "Consulta de niño sano", system: "http://snomed.info/sct" },
    '308516007': { display: "Control del adulto", system: "http://snomed.info/sct" },
    '409001005': { display: "Control del adulto mayor", system: "http://snomed.info/sct" },
    '281036007': { display: "Seguimiento médico", system: "http://snomed.info/sct" },
    '275926002': { display: "Cribado - control de salud", system: "http://snomed.info/sct" },
}

export enum CategoryType {
    AMB = "AMB",
    EMER = "EMER",
    FLD = "FLD",
    HH = "HH",
    IMP = "IMP",
    ACUTE = "ACUTE",
    NONAC = "NONAC",
    OBSENC = "OBSENC",
    PRENC = "PRENC",
    SS = "SS",
    VR = "VR"
}

export const categoryType = {
    'AMB': { display: "Ambulatory", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'EMER': { display: "Emergency", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'FLD': { display: "Field", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'HH': { display: "Home health", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'IMP': { display: "Inpatient encounter", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'ACUTE': { display: "Inpatient acute", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'NONAC': { display: "Inpatient non-acute", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'OBSENC': { display: "Observation encounter", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'PRENC': { display: "Pre-admission", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'SS': { display: "Short stay", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
    'VR': { display: "Virtual", system: "http://terminology.hl7.org/CodeSystem/v3-ActCode" },
}

export enum LengthCode {
    ms = 'ms',
    s = 's',
    min = 'min',
    h = 'h',
    d = 'd',
    wk = 'wk',
    mo = 'mo',
    a = 'a',
}

export const lengthCode = {
    'ms' : { unit : "seconds", system : "http://unitsofmeasure.org" },
    's' : { unit : "milliseconds", system : "http://unitsofmeasure.org" },
    'min' : { unit : "minutes", system : "http://unitsofmeasure.org" },
    'h' : { unit : "hours", system : "http://unitsofmeasure.org" },
    'd' : { unit : "days", system : "http://unitsofmeasure.org" },
    'wk' : { unit : "weeks", system : "http://unitsofmeasure.org" },
    'mo' : { unit : "months", system : "http://unitsofmeasure.org" },
    'a' : { unit : "years", system : "http://unitsofmeasure.org" }
}

export enum StatusUse {
    planned = 'planned',
    arrived = 'arrived',
    triaged = 'triaged',
    in_progress = 'in-progress',
    onleave = 'onleave',
    finished = 'finished',
    cancelled = 'cancelled',
    entered_in_error = 'entered-in-error',
    unknown = 'unknown'
}

export const statusUse = {
    planned : { display : "Planned" },
    arrived : { display : "Arrived" },
    triaged : { display : "Triaged" },
    in_progress : { display : "In Progress" },
    onleave : { display : "On Leave" },
    finished : { display : "Finished" },
    cancelled : { display : "Cancelled" },
    entered_in_error : { display : "Entered in Error" },
    unknown : { display : "Unknown" }
}


export const serviceTypeCode = [
    { code: "706317000", system: "http://snomed.info/sct", display: "Breast imaging system" },
    { code: "419815003", system: "http://snomed.info/sct", display: "Radiation oncology (qualifier value)" },
    { code: "310023006", system: "http://snomed.info/sct", display: "Radiotherapy service" },
    { code: "168537006", system: "http://snomed.info/sct", display: "Plain film" },
    { code: "74822006", system: "http://snomed.info/sct", display: "Recovering from" },
    { code: "733459009", system: "http://snomed.info/sct", display: "Cardiac rehabilitation service (qualifier value)" },
    { code: "312250003", system: "http://snomed.info/sct", display: "Magnetic resonance imaging" },
    { code: "394810000", system: "http://snomed.info/sct", display: "Rheumatology (qualifier value)" },
    { code: "419472004", system: "http://snomed.info/sct", display: "Pediatric rheumatology" },
    { code: "46224007", system: "http://snomed.info/sct", display: "Vaccination clinic" },
    { code: "710995003", system: "http://snomed.info/sct", display: "Monitoring pain (regime/therapy)" },
    { code: "392010000", system: "http://snomed.info/sct", display: "Optical coherence tomography (procedure)" },
    { code: "310128004", system: "http://snomed.info/sct", display: "Computerized tomography service" },
    { code: "702860000", system: "http://snomed.info/sct", display: "General surgery clinic (environment)" },
    { code: "702879002", system: "http://snomed.info/sct", display: "Laser eye clinic (environment)" },
    { code: "702862008", system: "http://snomed.info/sct", display: "Gynecology clinic (environment)" },
    { code: "718520009", system: "http://snomed.info/sct", display: "Intravenous infusion of iron (procedure)" },
    { code: "708170008", system: "http://snomed.info/sct", display: "Nursing service" },
    { code: "702931005", system: "http://snomed.info/sct", display: "Oncology clinic" },
    { code: "702852001", system: "http://snomed.info/sct", display: "Ear, nose and throat clinic" },
    { code: "702830005", system: "http://snomed.info/sct", display: "Cardiology clinic" },
    { code: "257585005", system: "http://snomed.info/sct", display: "Clinic" },
    { code: "702894003", system: "http://snomed.info/sct", display: "Ophthalmology clinic" },
    { code: "36125001", system: "http://snomed.info/sct", display: "Trauma center" },
    { code: "702928009", system: "http://snomed.info/sct", display: "Urology clinic (environment)" },
    { code: "241127009", system: "http://snomed.info/sct", display: "Encephalography" },
    { code: "702847006", system: "http://snomed.info/sct", display: "Dermatology clinic (environment)" },
    { code: "185251002", system: "http://snomed.info/sct", display: "Seen in EMG clinic" },
    { code: "57159002", system: "http://snomed.info/sct", display: "Hospital-based outpatient respiratory disease clinic" },
    { code: "702900003", system: "http://snomed.info/sct", display: "Pediatric clinic" },
    { code: "394801008", system: "http://snomed.info/sct", display: "Trauma & orthopaedics" },
    { code: "225390008", system: "http://snomed.info/sct", display: "Triage" },
    { code: "36228007", system: "http://snomed.info/sct", display: "Ophthalmic examination and evaluation" },
    { code: "183447000", system: "http://snomed.info/sct", display: "Admission to respiratory intensive care unit (procedure)" },
    { code: "830077005", system: "http://snomed.info/sct", display: "Admission to neonatal intensive care unit (procedure)" },
    { code: "305351004", system: "http://snomed.info/sct", display: "Admit to ITU" },
    { code: "305353001", system: "http://snomed.info/sct", display: "Admission to paediatric intensive care unit" },
    { code: "737563003", system: "http://snomed.info/sct", display: "Entire vertebral column and spinal cord (body structure)" },
    { code: "702910007", system: "http://snomed.info/sct", display: "Pelvic floor clinic (environment)" },
    { code: "252895004", system: "http://snomed.info/sct", display: "Urodynamics" },
    { code: "310167005", system: "http://snomed.info/sct", display: "Urology service" },
    { code: "419043006", system: "http://snomed.info/sct", display: "Urological oncology (qualifier value)" },
    { code: "453131000124105", system: "http://snomed.info/sct", display: "Videotelephony encounter (procedure)" },
    { code: "25931000087108", system: "http://snomed.info/sct", display: "Adolescent medicine (qualifier value)" },
    { code: "3751000175100", system: "http://snomed.info/sct", display: "Pediatric emergency medical service (qualifier value)" },
    { code: "410005002", system: "http://snomed.info/sct", display: "Dive medicine (qualifier value)" },
    { code: "1306761006", system: "http://snomed.info/sct", display: "Aesthetic medicine" },
    { code: "788121006", system: "http://snomed.info/sct", display: "Clinical immunology and allergy service" },
    { code: "1255517001", system: "http://snomed.info/sct", display: "Intern in healthcare (occupation)" },
    { code: "708184003", system: "http://snomed.info/sct", display: "Clinical pathology service (qualifier value)" },
    { code: "1163377005", system: "http://snomed.info/sct", display: "Breast milk feeding management" },
    { code: "71651007", system: "http://snomed.info/sct", display: "Mammography" },
    { code: "314463006", system: "http://snomed.info/sct", display: "24 hour blood pressure" },
    { code: "310060005", system: "http://snomed.info/sct", display: "Obstetrics and gynecology service" },
    { code: "419772000", system: "http://snomed.info/sct", display: "Family practice (qualifier value)" },
    { code: "773568002", system: "http://snomed.info/sct", display: "Emergency medicine (qualifier value)" },
    { code: "722424008", system: "http://snomed.info/sct", display: "Physical medicine and rehabilitation service (qualifier value)" },
    { code: "700232004", system: "http://snomed.info/sct", display: "General medical service" },
    { code: "310033003", system: "http://snomed.info/sct", display: "Adult ITU service" },
    { code: "310034009", system: "http://snomed.info/sct", display: "Pediatric ITU service" },
    { code: "792848000", system: "http://snomed.info/sct", display: "Internal medicine service" },
    { code: "788009005", system: "http://snomed.info/sct", display: "Nuclear medicine service" },
    { code: "394806003", system: "http://snomed.info/sct", display: "Palliative medicine (qualifier value)" },
    { code: "788003006", system: "http://snomed.info/sct", display: "Nephrology service" },
    { code: "3791000175107", system: "http://snomed.info/sct", display: "Pediatric nephrology service (qualifier value)" },
    { code: "408445005", system: "http://snomed.info/sct", display: "Neonatology (qualifier value)" },
    { code: "418112009", system: "http://snomed.info/sct", display: "Pulmonary medicine (qualifier value)" },
    { code: "419170002", system: "http://snomed.info/sct", display: "Pediatric pulmonology (qualifier value)" },
    { code: "310159002", system: "http://snomed.info/sct", display: "Neurosurgical service" },
    { code: "1280013002", system: "http://snomed.info/sct", display: "Paediatric neurosurgical service" },
    { code: "788005004", system: "http://snomed.info/sct", display: "Neurology service" },
    { code: "394538003", system: "http://snomed.info/sct", display: "Paediatric neurology" },
    { code: "722164000", system: "http://snomed.info/sct", display: "Dietetics and nutrition (qualifier value)" },
    { code: "722176000", system: "http://snomed.info/sct", display: "Dentistry service (qualifier value)" },
    { code: "310160007", system: "http://snomed.info/sct", display: "Ophthalmology service" },
    { code: "419983000", system: "http://snomed.info/sct", display: "Pediatric ophthalmology" },
    { code: "394593009", system: "http://snomed.info/sct", display: "Medical oncology (qualifier value)" },
    { code: "310069006", system: "http://snomed.info/sct", display: "Pediatric oncology service" },
    { code: "310105000", system: "http://snomed.info/sct", display: "Optometry service" },
    { code: "310149003", system: "http://snomed.info/sct", display: "Ear, nose and throat service" },
    { code: "789716007", system: "http://snomed.info/sct", display: "Pediatric otolaryngology service" },
    { code: "310066004", system: "http://snomed.info/sct", display: "Paediatric service" },
    { code: "722166003", system: "http://snomed.info/sct", display: "Podiatry (qualifier value)" },
    { code: "252777006", system: "http://snomed.info/sct", display: "Electric response audiometry" },
    { code: "63107007", system: "http://snomed.info/sct", display: "Visual evoked potential study" },
    { code: "278032008", system: "http://snomed.info/sct", display: "Preventive service" },
    { code: "373655009", system: "http://snomed.info/sct", display: "Medical service (procedure)" },
    { code: "722162001", system: "http://snomed.info/sct", display: "Psychology (qualifier value)" },
    { code: "394587001", system: "http://snomed.info/sct", display: "Psychiatry (qualifier value)" },
    { code: "315601005", system: "http://snomed.info/sct", display: "Ambulatory chemotherapy" },
    { code: "310125001", system: "http://snomed.info/sct", display: "Radiology service" },
    { code: "708174004", system: "http://snomed.info/sct", display: "Interventional radiology service (qualifier value)" },
    { code: "394811001", system: "http://snomed.info/sct", display: "Geriatric medicine (qualifier value)" },
    { code: "394586005", system: "http://snomed.info/sct", display: "Gynaecology" },
    { code: "1264044008", system: "http://snomed.info/sct", display: "Gynaecology oncology service" },
    { code: "394585009", system: "http://snomed.info/sct", display: "Obstetrics and gynaecology" },
    { code: "708196005", system: "http://snomed.info/sct", display: "Hematology service (qualifier value)" },
    { code: "418652005", system: "http://snomed.info/sct", display: "Pediatric hematology (qualifier value)" },
    { code: "1256098007", system: "http://snomed.info/sct", display: "Home hospitalization (qualifier value)" },
    { code: "40274000", system: "http://snomed.info/sct", display: "General outpatient clinic admission" },
    { code: "50849002", system: "http://snomed.info/sct", display: "Emergency room admission" },
    { code: "32485007", system: "http://snomed.info/sct", display: "Hospital admission" },
    { code: "408439002", system: "http://snomed.info/sct", display: "Allergy specialty (qualifier value)" },
    { code: "1255732006", system: "http://snomed.info/sct", display: "Anatomic pathology (qualifier value)" },
    { code: "394577000", system: "http://snomed.info/sct", display: "Anaesthetics" },
    { code: "310029005", system: "http://snomed.info/sct", display: "Domiciliary visit service" },
    { code: "310004004", system: "http://snomed.info/sct", display: "Audiological service" },
    { code: "50659003", system: "http://snomed.info/sct", display: "Medical audit procedure" },
    { code: "708194008", system: "http://snomed.info/sct", display: "Blood bank service" },
    { code: "86944008", system: "http://snomed.info/sct", display: "Visual field study" },
    { code: "394579002", system: "http://snomed.info/sct", display: "Cardiology (qualifier value)" },
    { code: "1251549008", system: "http://snomed.info/sct", display: "Interventional cardiology (qualifier value)" },
    { code: "408459003", system: "http://snomed.info/sct", display: "Paediatric cardiology" },
    { code: "424900004", system: "http://snomed.info/sct", display: "Recommendation - action (qualifier value)" },
    { code: "310030000", system: "http://snomed.info/sct", display: "Endoscopy service" },
    { code: "310063007", system: "http://snomed.info/sct", display: "Obstetrics service" },
    { code: "398156002", system: "http://snomed.info/sct", display: "Medical or surgical floor (environment)" },
    { code: "408456005", system: "http://snomed.info/sct", display: "Thoracic surgery (qualifier value)" },
    { code: "39380002", system: "http://snomed.info/sct", display: "Operation on neck and trunk" },
    { code: "110468005", system: "http://snomed.info/sct", display: "Ambulatory surgery" },
    { code: "1284930007", system: "http://snomed.info/sct", display: "Hand surgery (qualifier value)" },
    { code: "394609007", system: "http://snomed.info/sct", display: "General surgery (qualifier value)" },
    { code: "408469009", system: "http://snomed.info/sct", display: "Breast surgery (qualifier value)" },
    { code: "24061000087104", system: "http://snomed.info/sct", display: "Breast surgical oncology specialty (qualifier value)" },
    { code: "419321007", system: "http://snomed.info/sct", display: "Surgical oncology (qualifier value)" },
    { code: "394539006", system: "http://snomed.info/sct", display: "Paediatric surgery" },
    { code: "286553006", system: "http://snomed.info/sct", display: "Plastic operation" },
    { code: "56545009", system: "http://snomed.info/sct", display: "Cardiovascular surgeon" },
    { code: "236501004", system: "http://snomed.info/sct", display: "PFR - Pelvic floor repair" },
    { code: "408463005", system: "http://snomed.info/sct", display: "Vascular surgery (qualifier value)" },
    { code: "392003006", system: "http://snomed.info/sct", display: "Colposcopy (procedure)" },
    { code: "312681000", system: "http://snomed.info/sct", display: "Bone density scan" },
    { code: "23861000087105", system: "http://snomed.info/sct", display: "Adult dermatology" },
    { code: "23971000087106", system: "http://snomed.info/sct", display: "Paediatric dermatology" },
    { code: "310080006", system: "http://snomed.info/sct", display: "Pharmacy service" },
    { code: "40701008", system: "http://snomed.info/sct", display: "Echocardiography" },
    { code: "16310003", system: "http://snomed.info/sct", display: "Ultrasonography" },
    { code: "761884004", system: "http://snomed.info/sct", display: "Assessment using EuroSCORE (European System for Cardiac Operative Risk Evaluation)" },
    { code: "29303009", system: "http://snomed.info/sct", display: "Electrocardiographic procedure" },
    { code: "25876001", system: "http://snomed.info/sct", display: "Emergency" },
    { code: "394583002", system: "http://snomed.info/sct", display: "Endocrinology (qualifier value)" },
    { code: "419610006", system: "http://snomed.info/sct", display: "Pediatric endocrinology" },
    { code: "788001008", system: "http://snomed.info/sct", display: "Infectious disease service (qualifier value)" },
    { code: "722165004", system: "http://snomed.info/sct", display: "Nursing (qualifier value)" },
    { code: "1231393002", system: "http://snomed.info/sct", display: "Spirometry service" },
    { code: "389093003", system: "http://snomed.info/sct", display: "Fertility care (regime/therapy)" },
    { code: "448764002", system: "http://snomed.info/sct", display: "Ultrasound elastography (procedure)" },
    { code: "418058008", system: "http://snomed.info/sct", display: "Pediatric gastroenterology" },
    { code: "394584008", system: "http://snomed.info/sct", display: "Gastroenterology (qualifier value)" },
    { code: "310048009", system: "http://snomed.info/sct", display: "Genetics service	inactive" },
    { code: "310054005", system: "http://snomed.info/sct", display: "Infectious diseases service" }
];
