steps:
  - id: "Build Application"
    name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args: ["-c", "npm install && npm run build"]

  - id: "test"
    name: "gcr.io/cloud-builders/npm"
    args: ["test", "--", "--coverage"]

  - id: "sonar-analysis"
    name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "${BRANCH_NAME}" == "develop" ]]; then
          node sonar-project.js
        else
          echo "Skipping SonarQube analysis for branch ${BRANCH_NAME}"
        fi
    env:
      - "SONAR_HOST_URL=${_SONAR_HOST_URL}"
      - "SONAR_PROJECT_KEY=${_SONAR_PROJECT_KEY}"
      - "SONAR_PROJECT_NAME=${_SONAR_PROJECT_NAME}"
      - "SONAR_PROJECT_VERSION=${_VERSION}"
    secretEnv: ["SONAR_TOKEN"]
    waitFor: ["test"]

  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag",
        "us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/msa-ne-clinicalsummary-allergy-intolerance:$COMMIT_SHA",
        "-f",
        "./deploy/Dockerfile",
        "./",
      ]

  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/msa-ne-clinicalsummary-allergy-intolerance:$COMMIT_SHA",
      ]

  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "msa-ne-clinicalsummary-allergy-intolerance-service",
        "--image",
        "us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/msa-ne-clinicalsummary-allergy-intolerance:$COMMIT_SHA",
        "--port",
        "3333",
        "--platform",
        "managed",
        "--region",
        "us-east1",
        "--allow-unauthenticated",
        "--ingress",
        "internal",
        "--project",
        "attpltfrm-dev-apiscore",
        "--max-instances",
        "3",
        "--network",
        "projects/compass-net-dev-shared-vpc/global/networks/compass-net-dev-shared-vpc",
        "--subnet",
        "projects/compass-net-dev-shared-vpc/regions/us-east1/subnetworks/subnet-shared-us-east1-dev-apiscore",
        "--set-env-vars",
        "FHIR_BASE=https://healthcare.googleapis.com/v1/",
        "--set-env-vars",
        "FHIR_PROJECT=projects/compass-dev-inter/locations/us-east1/datasets/hds-inter-sp-dataset/fhirStores/fhir-inter-sp-armonizado",
        "--set-env-vars",
        "FIREBASE_PROJECT_ID=attpltfrm-dev-apiscore",
        "--set-env-vars",
        "FIRESTORE_BD_CONFIGURATION=fire-configuration-fhir",
        "--set-env-vars",
        "FIRESTORE_BD_TRACKING=fire-tracking-fhir",
        "--service-account",
        "gsa-app-sp-backend@attpltfrm-dev-apiscore.iam.gserviceaccount.com",
        "--quiet",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/attpltfrm-dev-apiscore/secrets/sonar-token/versions/latest
      env: "SONAR_TOKEN"

substitutions:
  _SONAR_HOST_URL: "https://sonarqube.cuidaco.pe"
  _SONAR_PROJECT_KEY: "Rimac-Compass_attpltfrm-msa-ne-clinicalsummary-allergy-intolerance_16a12952-78ad-4623-8a1a-868d8cb971ba"
  _SONAR_PROJECT_NAME: "Attpltfrm MSA NE Clinical Summary Allergy Intolerance"
  _VERSION: "1.0.0"

logsBucket: "gs://shared-dev-cloud-build"
options:
  logging: GCS_ONLY
  automapSubstitutions: true
