steps:
  - id: 'Build Application'
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: ['-c', 'npm install && npm run build']

  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/attpltfrm-msa-ne-administration-encounters:$COMMIT_SHA', '-f', './deploy/Dockerfile', './']

  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/attpltfrm-msa-ne-administration-encounters:$COMMIT_SHA']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'msa-ne-administration-encounters-service',
        '--image', 'us-east1-docker.pkg.dev/attpltfrm-dev-apiscore/dev-app-artifact-registry/attpltfrm-msa-ne-administration-encounters:$COMMIT_SHA',
        '--port', '3333',
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',
        '--ingress', 'internal',
        '--project', 'attpltfrm-dev-apiscore',
        '--max-instances', '3',
        '--network', 'projects/compass-net-dev-shared-vpc/global/networks/compass-net-dev-shared-vpc',
        '--subnet', 'projects/compass-net-dev-shared-vpc/regions/us-east1/subnetworks/subnet-shared-us-east1-dev-apiscore',
        '--set-env-vars','FHIR_BASE=https://healthcare.googleapis.com/v1/',
        '--set-env-vars','FHIR_PROJECT=projects/compass-dev-inter/locations/us-east1/datasets/hds-inter-sp-dataset/fhirStores/fhir-inter-sp-armonizado',
        '--service-account', 'gsa-app-sp-backend@attpltfrm-dev-apiscore.iam.gserviceaccount.com',
        '--quiet'
      ]

logsBucket: 'gs://compass-dev-app-cloud-build'
serviceAccount: 'gsa-app-sp-backend@attpltfrm-dev-apiscore.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
  automapSubstitutions: true